/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ca_fraggergames_ffxivextract_Main */

#ifndef _Included_ca_fraggergames_ffxivextract_Main
#define _Included_ca_fraggergames_ffxivextract_Main
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
