/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ca_fraggergames_ffxivextract_helpers_LuaDec */

#ifndef _Included_ca_fraggergames_ffxivextract_helpers_LuaDec
#define _Included_ca_fraggergames_ffxivextract_helpers_LuaDec
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ca_fraggergames_ffxivextract_helpers_LuaDec
 * Method:    decompile
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ca_fraggergames_ffxivextract_helpers_LuaDec_decompile
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
